# Generated by Django 5.2.15 on 2026-08-16 16:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aero_clients', '0001_initial'),
        ('aero_maintenance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeDAE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=50, unique=True)),
                ('type_intervention', models.CharField(choices=[('PREVENTIVE', 'Maintenance préventive'), ('CORRECTIVE', 'Maintenance corrective'), ('URGENCE', 'Urgence')], default='CORRECTIVE', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('urgence', models.CharField(choices=[('NORMALE', 'Normale'), ('HAUTE', 'Haute'), ('URGENTE', 'Urgente')], default='NORMALE', max_length=10)),
                ('statut', models.CharField(choices=[('NOUVELLE', 'Nouvelle'), ('A_ETUDIER', 'À étudier'), ('ACCEPTEE', 'Acceptée'), ('REFUSEE', 'Refusée'), ('EN_TRAITEMENT', 'En traitement')], default='NOUVELLE', max_length=20)),
                ('date_reception', models.DateTimeField(auto_now_add=True)),
                ('date_traitement', models.DateTimeField(blank=True, null=True)),
                ('aeronef', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes', to='aero_clients.aeronef')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes', to='aero_clients.clientaeronautique')),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('ordre_travail', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demande', to='aero_maintenance.ordretravail')),
            ],
            options={
                'ordering': ['-date_reception'],
            },
        ),
    ]
