# Generated by Django 5.2.15 on 2026-08-16 17:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aero_clients', '0002_demandedae'),
        ('aero_maintenance', '0003_interventiontechnique'),
    ]

    operations = [
        migrations.CreateModel(
            name='SatisfactionDAE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('note_qualite', models.PositiveSmallIntegerField(blank=True, help_text='Note sur 5', null=True)),
                ('note_delai', models.PositiveSmallIntegerField(blank=True, help_text='Note sur 5', null=True)),
                ('note_accueil', models.PositiveSmallIntegerField(blank=True, help_text='Note sur 5', null=True)),
                ('note_communication', models.PositiveSmallIntegerField(blank=True, help_text='Note sur 5', null=True)),
                ('note_prestation_technique', models.PositiveSmallIntegerField(blank=True, help_text='Note sur 5', null=True)),
                ('commentaire', models.TextField(blank=True)),
                ('date_envoi', models.DateTimeField(blank=True, null=True)),
                ('date_evaluation', models.DateTimeField(blank=True, null=True)),
                ('ordre_travail', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='satisfaction', to='aero_maintenance.ordretravail')),
            ],
            options={
                'ordering': ['-date_envoi'],
            },
        ),
    ]
