# Generated by Django 5.2.15 on 2026-08-16 18:04

import django.db.models.deletion
from django.db import migrations, models


def backfill_client_codes(apps, schema_editor):
    """Le champ code (unique) est ajoute sans contrainte unique dans un
    premier temps pour pouvoir backfiller les lignes existantes sans
    collision (toutes partiraient de la meme valeur '' sinon)."""
    ClientAeronautique = apps.get_model('aero_clients', 'ClientAeronautique')
    for i, client in enumerate(ClientAeronautique.objects.order_by('id'), start=1):
        client.code = f"CLI-DAE-{i:04d}"
        client.save(update_fields=['code'])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('aero_clients', '0003_satisfactiondae'),
    ]

    operations = [
        migrations.AddField(
            model_name='aeronef',
            name='annee_fabrication',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aeronef',
            name='constructeur',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='aeronef',
            name='modele',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='aeronef',
            name='nombre_cycles',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='aeronef',
            name='nombre_heures_vol',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='aeronef',
            name='numero_serie',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='aeronef',
            name='proprietaire',
            field=models.CharField(blank=True, help_text="Si différent de l'exploitant (client)", max_length=255),
        ),
        migrations.AddField(
            model_name='clientaeronautique',
            name='adresse',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='clientaeronautique',
            name='code',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='clientaeronautique',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='clientaeronautique',
            name='numero_identification',
            field=models.CharField(blank=True, help_text='RCCM, NIF ou équivalent', max_length=100),
        ),
        migrations.AddField(
            model_name='clientaeronautique',
            name='telephone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='clientaeronautique',
            name='type_client',
            field=models.CharField(choices=[('COMPAGNIE_AERIENNE', 'Compagnie aérienne'), ('FORCES_ARMEES', 'Forces armées'), ('ADMINISTRATION', 'Administration'), ('SOCIETE_MAINTENANCE', 'Société de maintenance aéronautique'), ('AEROCLUB', 'Aéroclub'), ('OPERATEUR_PRIVE', 'Opérateur privé'), ('ORGANISME_PUBLIC', 'Organisme public'), ('AUTRE', 'Autre')], default='AUTRE', max_length=25),
        ),
        migrations.AlterField(
            model_name='aeronef',
            name='client',
            field=models.ForeignKey(blank=True, help_text='Exploitant', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aeronefs', to='aero_clients.clientaeronautique'),
        ),
        migrations.AlterField(
            model_name='clientaeronautique',
            name='contact',
            field=models.CharField(blank=True, help_text='Personne responsable', max_length=255),
        ),
        migrations.RunPython(backfill_client_codes, noop),
        migrations.AlterField(
            model_name='clientaeronautique',
            name='code',
            field=models.CharField(blank=True, max_length=30, unique=True),
        ),
    ]
