# Generated by Django 6.0.5 on 2026-08-16 18:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_reclamation_references(apps, schema_editor):
    """Le champ reference (unique) est ajoute sans contrainte unique dans un
    premier temps pour pouvoir backfiller les lignes existantes sans
    collision — meme pattern que ClientAeronautique.code (migration 0004)."""
    ReclamationClientDAE = apps.get_model('aero_clients', 'ReclamationClientDAE')
    for i, reclamation in enumerate(ReclamationClientDAE.objects.order_by('id'), start=1):
        annee = reclamation.date_reception.year if reclamation.date_reception else 2026
        reclamation.reference = f"RECL-DAE-{annee}-{i:05d}"
        reclamation.save(update_fields=['reference'])


def remap_statut(apps, schema_editor):
    """OUVERTE -> ENREGISTREE, TRAITEE -> CLOTUREE (ancien modele a 2 etats ->
    workflow detaille section 22 du cahier des charges)."""
    ReclamationClientDAE = apps.get_model('aero_clients', 'ReclamationClientDAE')
    ReclamationClientDAE.objects.filter(statut='OUVERTE').update(statut='ENREGISTREE')
    ReclamationClientDAE.objects.filter(statut='TRAITEE').update(statut='CLOTUREE')


def revert_statut(apps, schema_editor):
    ReclamationClientDAE = apps.get_model('aero_clients', 'ReclamationClientDAE')
    ReclamationClientDAE.objects.filter(statut='ENREGISTREE').update(statut='OUVERTE')
    ReclamationClientDAE.objects.filter(statut='CLOTUREE').update(statut='TRAITEE')


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('aero_clients', '0004_aeronef_annee_fabrication_aeronef_constructeur_and_more'),
        ('aero_maintenance', '0006_certificatdae'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reclamationclientdae',
            name='analyse',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='reclamationclientdae',
            name='date_reponse',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reclamationclientdae',
            name='ordre_travail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reclamations', to='aero_maintenance.ordretravail'),
        ),
        migrations.AddField(
            model_name='reclamationclientdae',
            name='reference',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='reclamationclientdae',
            name='reponse',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='reclamationclientdae',
            name='responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reclamations_dae', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reclamationclientdae',
            name='type_reclamation',
            field=models.CharField(choices=[('RETARD', 'Retard'), ('PROBLEME_TECHNIQUE', 'Problème technique'), ('PROBLEME_ADMINISTRATIF', 'Problème administratif'), ('PROBLEME_FACTURATION', 'Problème de facturation'), ('QUALITE_INSUFFISANTE', 'Qualité insuffisante'), ('AUTRE', 'Autre')], default='AUTRE', max_length=25),
        ),
        migrations.AlterField(
            model_name='reclamationclientdae',
            name='date_traitement',
            field=models.DateField(blank=True, help_text='Date de clôture', null=True),
        ),
        migrations.AlterField(
            model_name='reclamationclientdae',
            name='statut',
            field=models.CharField(choices=[('ENREGISTREE', 'Enregistrée'), ('EN_ANALYSE', 'En analyse'), ('AFFECTEE', 'Affectée'), ('EN_TRAITEMENT', 'En traitement'), ('REPONSE_ENVOYEE', 'Réponse envoyée'), ('CLOTUREE', 'Clôturée')], default='ENREGISTREE', max_length=20),
        ),
        migrations.RunPython(remap_statut, revert_statut),
        migrations.RunPython(backfill_reclamation_references, noop),
        migrations.AlterField(
            model_name='reclamationclientdae',
            name='reference',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
