# Generated by Django 6.0.5 on 2026-08-16 21:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aero_clients', '0005_reclamationclientdae_analyse_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='clientaeronautique',
            name='compte_utilisateur',
            field=models.OneToOneField(blank=True, help_text='Compte du portail client DAE lié à cette organisation (cf. cahier des charges section 3.7)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_aeronautique', to=settings.AUTH_USER_MODEL),
        ),
    ]
