# Generated by Django 4.2.17 on 2025-06-06 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='qr_code',
            field=models.ImageField(blank=True, help_text="QR code de l'agent", null=True, upload_to='qrcodes/'),
        ),
    ]
