# Generated by Django 4.2.17 on 2025-06-06 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_userprofile_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='matricule',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
