# Generated by Django 4.2.23 on 2025-06-26 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_agent_qr_code_remove_presence_qr_code_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='telephone',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
    ]
