# Generated by Django 4.2.23 on 2025-06-27 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_userprofile_telephone'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='empreinte_hash',
            field=models.TextField(blank=True, null=True),
        ),
    ]
