# Generated by Django 4.2.23 on 2025-07-04 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_userprofile_empreinte_hash'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='empreinte_hash',
        ),
        migrations.AddField(
            model_name='agent',
            name='empreinte_hash',
            field=models.TextField(blank=True, help_text="Hash de l'empreinte digitale de l'agent", null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='localisation_valide',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='agent',
            name='bureau',
            field=models.CharField(blank=True, help_text='Nom ou référence du bureau', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='latitude_centre',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Latitude du centre du bureau', max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='longitude_centre',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Longitude du centre du bureau', max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='service',
            field=models.ForeignKey(blank=True, help_text='Service de rattachement', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.service'),
        ),
    ]
