# Generated by Django 4.2.23 on 2025-07-04 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_userprofile_empreinte_hash_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='role',
        ),
    ]
