# Generated by Django 4.2.23 on 2025-07-04 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_agent_localisation_valide'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bureau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Nom ou référence du bureau', max_length=255, unique=True)),
                ('latitude_centre', models.DecimalField(decimal_places=6, help_text='Latitude du centre du bureau', max_digits=9)),
                ('longitude_centre', models.DecimalField(decimal_places=6, help_text='Longitude du centre du bureau', max_digits=9)),
                ('rayon_metres', models.IntegerField(help_text='Rayon de la zone autorisée en mètres')),
            ],
        ),
        migrations.RemoveField(
            model_name='agent',
            name='latitude_centre',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='longitude_centre',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='rayon_metres',
        ),
        migrations.AlterField(
            model_name='agent',
            name='bureau',
            field=models.ForeignKey(blank=True, help_text="Bureau de rattachement de l'agent", null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.bureau'),
        ),
    ]
