# Generated by Django 4.2.23 on 2025-07-05 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_bureau_remove_agent_latitude_centre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='empreinte_hash',
            field=models.CharField(blank=True, help_text="Hash de l'empreinte digitale de l'utilisateur", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bureau',
            name='latitude_centre',
            field=models.DecimalField(decimal_places=17, help_text='Latitude du centre du bureau', max_digits=22),
        ),
        migrations.AlterField(
            model_name='bureau',
            name='longitude_centre',
            field=models.DecimalField(decimal_places=17, help_text='Longitude du centre du bureau', max_digits=22),
        ),
    ]
