# Generated by Django 4.2.7 on 2025-09-22 16:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0011_userprofile_empreinte_hash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courrier',
            name='sens',
            field=models.CharField(choices=[('arrivee', 'Arrivée'), ('depart', 'Départ')], default='arrivee', max_length=20),
        ),
        migrations.AddField(
            model_name='courrier',
            name='type_courrier',
            field=models.CharField(choices=[('ordinaire', 'Ordinaire'), ('confidentiel', 'Confidentiel')], default='ordinaire', max_length=20),
        ),
        migrations.CreateModel(
            name='CourrierAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('courrier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_permissions', to='core.courrier')),
                ('granted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='granted_courrier_access', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courrier_access', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Accès Courrier',
                'verbose_name_plural': 'Accès Courriers',
                'unique_together': {('courrier', 'user')},
            },
        ),
    ]
