# Generated by Django 4.2.7 on 2025-09-22 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_courrier_sens_courrier_type_courrier_courrieraccess'),
    ]

    operations = [
        migrations.AddField(
            model_name='courrier',
            name='destinataire',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
