# Generated by Django 4.2.7 on 2025-09-22 21:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0013_courrier_destinataire'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('type_activite', models.CharField(choices=[('atelier', 'Atelier'), ('seminaire', 'Séminaire'), ('colloque', 'Colloque'), ('reunion', 'Réunion'), ('ceremonie', 'Cérémonie'), ('autre', 'Autre')], default='autre', max_length=20)),
                ('date_debut', models.DateField()),
                ('date_fin_prevue', models.DateField()),
                ('date_fin_effective', models.DateField(blank=True, null=True)),
                ('etat', models.CharField(choices=[('planifiee', 'Planifiée'), ('en_cours', 'En cours'), ('terminee', 'Terminée'), ('suspendue', 'Suspendue')], default='planifiee', max_length=20)),
                ('lieu', models.CharField(blank=True, max_length=255, null=True)),
                ('budget_previsionnel', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('nombre_participants_prevu', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('responsable_principal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activites_responsable', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.service')),
            ],
            options={
                'verbose_name': 'Activité',
                'verbose_name_plural': 'Activités',
            },
        ),
        migrations.CreateModel(
            name='Domaine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_debut', models.DateField()),
                ('date_fin_prevue', models.DateField()),
                ('date_fin_effective', models.DateField(blank=True, null=True)),
                ('pourcentage_avancement', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domaines', to='core.activite')),
                ('superviseur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='domaines_supervises', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Domaine',
                'verbose_name_plural': 'Domaines',
            },
        ),
        migrations.AddField(
            model_name='tache',
            name='date_debut',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tache',
            name='date_fin_effective',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tache',
            name='date_fin_prevue',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tache',
            name='domaine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='taches', to='core.domaine'),
        ),
        migrations.AddField(
            model_name='tache',
            name='pourcentage_avancement',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='tache',
            name='tache_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sous_taches', to='core.tache'),
        ),
        migrations.AlterField(
            model_name='tache',
            name='projet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.projet'),
        ),
    ]
