# Generated by Django 4.2.7 on 2025-09-22 21:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0014_auto_20250922_2104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projet',
            name='agents',
        ),
        migrations.RemoveField(
            model_name='projet',
            name='directeurs',
        ),
        migrations.RemoveField(
            model_name='projet',
            name='secretaires',
        ),
        migrations.RemoveField(
            model_name='projet',
            name='superieurs',
        ),
        migrations.RemoveField(
            model_name='tache',
            name='agentsAffectes',
        ),
        migrations.RemoveField(
            model_name='tache',
            name='dateDebut',
        ),
        migrations.RemoveField(
            model_name='tache',
            name='dateEcheance',
        ),
        migrations.RemoveField(
            model_name='tache',
            name='parentTache',
        ),
        migrations.AlterField(
            model_name='tache',
            name='agents',
            field=models.ManyToManyField(blank=True, related_name='agents_taches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tache',
            name='directeurs',
            field=models.ManyToManyField(blank=True, related_name='directeurs_taches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tache',
            name='etat',
            field=models.CharField(choices=[('a_faire', 'À faire'), ('en_attente', 'En attente'), ('en_cours', 'En cours'), ('terminee', 'Terminée'), ('annulee', 'Annulée')], default='a_faire', max_length=20),
        ),
        migrations.AlterField(
            model_name='tache',
            name='priorite',
            field=models.CharField(choices=[('basse', 'Basse'), ('moyenne', 'Moyenne'), ('haute', 'Haute')], default='moyenne', max_length=20),
        ),
        migrations.AlterField(
            model_name='tache',
            name='secretaires',
            field=models.ManyToManyField(blank=True, related_name='secretaires_taches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tache',
            name='superieurs',
            field=models.ManyToManyField(blank=True, related_name='superieurs_taches', to=settings.AUTH_USER_MODEL),
        ),
    ]
