# Generated by Django 4.2.7 on 2025-09-22 22:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0015_remove_projet_agents_remove_projet_directeurs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diligence',
            name='date_rappel_1',
            field=models.DateField(blank=True, help_text='Premier rappel avant échéance', null=True),
        ),
        migrations.AddField(
            model_name='diligence',
            name='date_rappel_2',
            field=models.DateField(blank=True, help_text='Deuxième rappel avant échéance', null=True),
        ),
        migrations.AddField(
            model_name='diligence',
            name='domaine',
            field=models.CharField(choices=[('representations', 'Représentations'), ('projet_x', 'Projet X'), ('projet_y', 'Projet Y'), ('atelier', 'Atelier'), ('evenements', 'Événements'), ('formation', 'Formation'), ('communication', 'Communication'), ('logistique', 'Logistique'), ('budget', 'Budget'), ('autre', 'Autre')], default='autre', max_length=50),
        ),
        migrations.AddField(
            model_name='diligence',
            name='pourcentage_avancement',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='diligence',
            name='type_diligence',
            field=models.CharField(choices=[('courrier', 'Basée sur courrier'), ('spontanee', 'Spontanée')], default='courrier', max_length=20),
        ),
        migrations.AddField(
            model_name='diligence',
            name='validated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diligences_validated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='DiligenceNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_notification', models.CharField(choices=[('rappel_delai', 'Rappel de délai'), ('nouvelle_diligence', 'Nouvelle diligence'), ('validation_requise', 'Validation requise'), ('document_valide', 'Document validé'), ('diligence_archivee', 'Diligence archivée')], max_length=30)),
                ('message', models.TextField()),
                ('read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('diligence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='core.diligence')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diligence_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification de Diligence',
                'verbose_name_plural': 'Notifications de Diligence',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DiligenceDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('contenu', models.TextField(blank=True, help_text="Contenu éditable directement dans l'application", null=True)),
                ('fichier', models.FileField(blank=True, null=True, upload_to='diligence_documents/')),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('en_revision', 'En révision'), ('valide', 'Validé'), ('archive', 'Archivé')], default='brouillon', max_length=20)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents_created', to=settings.AUTH_USER_MODEL)),
                ('diligence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core.diligence')),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_validated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document de Diligence',
                'verbose_name_plural': 'Documents de Diligence',
                'ordering': ['-created_at'],
            },
        ),
    ]
