# Generated by Django 4.2.7 on 2025-09-24 16:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0016_diligence_date_rappel_1_diligence_date_rappel_2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDiligenceInstruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instruction', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('diligence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_instructions', to='core.diligence')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diligence_instructions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Diligence Instruction',
                'verbose_name_plural': 'User Diligence Instructions',
                'unique_together': {('diligence', 'user')},
            },
        ),
        migrations.CreateModel(
            name='UserDiligenceComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('diligence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_comments', to='core.diligence')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diligence_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Diligence Comment',
                'verbose_name_plural': 'User Diligence Comments',
                'unique_together': {('diligence', 'user')},
            },
        ),
    ]
