# Generated by Django 4.2.7 on 2025-09-24 20:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0017_userdiligenceinstruction_userdiligencecomment'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeConge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_conge', models.CharField(choices=[('annuel', 'Congé annuel'), ('maladie', 'Congé maladie'), ('maternite', 'Congé maternité'), ('paternite', 'Congé paternité'), ('sans_solde', 'Congé sans solde'), ('formation', 'Congé formation'), ('exceptionnel', 'Congé exceptionnel')], max_length=20)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('nombre_jours', models.PositiveIntegerField()),
                ('motif', models.TextField()),
                ('adresse_conge', models.TextField(help_text='Adresse pendant le congé')),
                ('telephone_conge', models.CharField(help_text='Téléphone pendant le congé', max_length=20)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('approuve', 'Approuvé'), ('rejete', 'Rejeté'), ('annule', 'Annulé')], default='en_attente', max_length=20)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('commentaire_validation', models.TextField(blank=True, null=True)),
                ('document_demande', models.FileField(blank=True, null=True, upload_to='conges/demandes/')),
                ('document_reponse', models.FileField(blank=True, null=True, upload_to='conges/reponses/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('demandeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_conge', to=settings.AUTH_USER_MODEL)),
                ('superieur_hierarchique', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conges_a_valider', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Demande de congé',
                'verbose_name_plural': 'Demandes de congé',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DemandeAbsence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_absence', models.CharField(choices=[('personnelle', 'Raison personnelle'), ('medicale', 'Rendez-vous médical'), ('familiale', 'Raison familiale'), ('administrative', 'Démarche administrative'), ('formation', 'Formation'), ('mission', 'Mission'), ('autre', 'Autre')], max_length=20)),
                ('date_debut', models.DateTimeField()),
                ('date_fin', models.DateTimeField()),
                ('duree_heures', models.DecimalField(decimal_places=2, help_text='Durée en heures', max_digits=4)),
                ('motif', models.TextField()),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('approuve', 'Approuvé'), ('rejete', 'Rejeté'), ('annule', 'Annulé')], default='en_attente', max_length=20)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('commentaire_validation', models.TextField(blank=True, null=True)),
                ('document_demande', models.FileField(blank=True, null=True, upload_to='absences/demandes/')),
                ('document_reponse', models.FileField(blank=True, null=True, upload_to='absences/reponses/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('demandeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_absence', to=settings.AUTH_USER_MODEL)),
                ('superieur_hierarchique', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='absences_a_valider', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Demande d'absence",
                'verbose_name_plural': "Demandes d'absence",
                'ordering': ['-created_at'],
            },
        ),
    ]
