# Generated by Django 4.2.7 on 2025-09-24 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_demandeconge_demandeabsence'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandeabsence',
            name='agents_concernes',
            field=models.ManyToManyField(blank=True, help_text='Agents de la même direction/service informés de cette absence', related_name='absences_concernes', to='auth.user'),
        ),
    ]
