# Generated by Django 4.2.7 on 2025-09-25 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_add_demandeconge_agents_concernes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='demandeconge',
            options={'ordering': ['-date_creation'], 'verbose_name': 'Demande de congé', 'verbose_name_plural': 'Demandes de congé'},
        ),
    ]
