# Generated by Django 4.2.7 on 2025-09-25 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_demandeconge_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='diligencenotification',
            name='lien',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='diligencenotification',
            name='diligence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='core.diligence'),
        ),
        migrations.AlterField(
            model_name='diligencenotification',
            name='type_notification',
            field=models.CharField(choices=[('rappel_delai', 'Rappel de délai'), ('nouvelle_diligence', 'Nouvelle diligence'), ('validation_requise', 'Validation requise'), ('document_valide', 'Document validé'), ('diligence_archivee', 'Diligence archivée'), ('conges_validation', 'Validation de congé'), ('conges_rejet', 'Rejet de congé'), ('absences_validation', "Validation d'absence"), ('absences_rejet', "Rejet d'absence")], max_length=30),
        ),
    ]
