# Generated by Django 4.2.7 on 2025-09-27 10:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0024_alter_notification_options_notification_contenu_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandeabsence',
            name='directeur',
            field=models.ForeignKey(blank=True, help_text='Directeur sélectionné', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='absences_directeur', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='demandeabsence',
            name='emploi',
            field=models.CharField(default='', help_text='Emploi occupé', max_length=100),
        ),
        migrations.AddField(
            model_name='demandeabsence',
            name='fonction',
            field=models.CharField(default='', help_text='Fonction exercée', max_length=100),
        ),
        migrations.AddField(
            model_name='demandeabsence',
            name='matricule',
            field=models.CharField(default='', help_text="Matricule de l'agent", max_length=50),
        ),
        migrations.AddField(
            model_name='demandeabsence',
            name='superieur',
            field=models.ForeignKey(blank=True, help_text='Supérieur hiérarchique sélectionné', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='absences_superieur', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='demandeconge',
            name='directeur',
            field=models.ForeignKey(blank=True, help_text='Directeur sélectionné', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conges_directeur', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='demandeconge',
            name='emploi',
            field=models.CharField(default='', help_text='Emploi occupé', max_length=100),
        ),
        migrations.AddField(
            model_name='demandeconge',
            name='fonction',
            field=models.CharField(default='', help_text='Fonction exercée', max_length=100),
        ),
        migrations.AddField(
            model_name='demandeconge',
            name='matricule',
            field=models.CharField(default='', help_text="Matricule de l'agent", max_length=50),
        ),
        migrations.AddField(
            model_name='demandeconge',
            name='superieur',
            field=models.ForeignKey(blank=True, help_text='Supérieur hiérarchique sélectionné', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conges_superieur', to=settings.AUTH_USER_MODEL),
        ),
    ]
