# Generated by Django 4.2.7 on 2025-09-27 12:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0025_demandeabsence_directeur_demandeabsence_emploi_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourrierImputation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_type', models.CharField(choices=[('view', 'Lecture'), ('edit', 'Édition')], default='view', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('courrier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imputation_access', to='core.courrier')),
                ('granted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='granted_courrier_imputation', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courrier_imputation_access', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Imputation Courrier',
                'verbose_name_plural': 'Imputations Courriers',
                'unique_together': {('courrier', 'user', 'access_type')},
            },
        ),
    ]
