# Generated by Django 4.2.7 on 2025-09-29 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_courrierimputation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presence',
            name='empreinte_hash',
        ),
    ]
