# Generated by Django 4.2.7 on 2025-09-30 12:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0027_remove_fingerprint_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='presence',
            name='device_fingerprint',
            field=models.CharField(blank=True, help_text='Empreinte unique du téléphone', max_length=64, null=True),
        ),
        migrations.CreateModel(
            name='DeviceRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_fingerprint', models.CharField(help_text='Empreinte unique du téléphone', max_length=64, unique=True)),
                ('device_name', models.CharField(blank=True, help_text="Nom de l'appareil (optionnel)", max_length=100)),
                ('first_used', models.DateTimeField(auto_now_add=True)),
                ('last_used', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registered_devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Appareil enregistré',
                'verbose_name_plural': 'Appareils enregistrés',
                'unique_together': {('user', 'device_fingerprint')},
            },
        ),
    ]
