
# Generated by Django 4.2.7 on 2025-10-01 12:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0028_presence_device_fingerprint_deviceregistration'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeofenceSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heure_debut_matin', models.TimeField(default='07:30', help_text='Début des heures de travail du matin')),
                ('heure_fin_matin', models.TimeField(default='12:30', help_text='Fin des heures de travail du matin')),
                ('heure_debut_apres_midi', models.TimeField(default='13:30', help_text="Début des heures de travail de l'après-midi")),
                ('heure_fin_apres_midi', models.TimeField(default='16:30', help_text="Fin des heures de travail de l'après-midi")),
                ('distance_alerte_metres', models.IntegerField(default=200, help_text='Distance en mètres pour déclencher une alerte')),
                ('duree_minimale_hors_bureau_minutes', models.IntegerField(default=60, help_text='Durée minimale hors du bureau en minutes avant alerte')),
                ('frequence_verification_minutes', models.IntegerField(default=5, help_text='Fréquence de vérification de la position en minutes')),
                ('lundi_travaille', models.BooleanField(default=True)),
                ('mardi_travaille', models.BooleanField(default=True)),
                ('mercredi_travaille', models.BooleanField(default=True)),
                ('jeudi_travaille', models.BooleanField(default=True)),
                ('vendredi_travaille', models.BooleanField(default=True)),
                ('samedi_travaille', models.BooleanField(default=False)),
                ('dimanche_travaille', models.BooleanField(default=False)),
                ('notification_directeurs', models.BooleanField(default=True, help_text='Envoyer des notifications aux directeurs')),
                ('notification_superieurs', models.BooleanField(default=True, help_text='Envoyer des notifications aux supérieurs')),
                ('notification_push_active', models.BooleanField(default=True, help_text='Activer les notifications push')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuration géofencing',
                'verbose_name_plural': 'Configurations géofencing',
            },
        ),
        migrations.CreateModel(
            name='PushNotificationToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(help_text='Token FCM/APNS', max_length=500, unique=True)),
                ('platform', models.CharField(choices=[('android', 'Android'), ('ios', 'iOS'), ('web', 'Web')], max_length=10)),
                ('device_id', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Token de notification push',
                'verbose_name_plural': 'Tokens de notification push',
            },
        ),
        migrations.CreateModel(
            name='GeofenceAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_alerte', models.CharField(choices=[('sortie_zone', 'Sortie de zone'), ('entree_zone', 'Entrée en zone'), ('hors_horaires', 'Hors horaires de travail')], default='sortie_zone', max_length=20)),
                ('latitude_agent', models.DecimalField(decimal_places=17, max_digits=22)),
                ('longitude_agent', models.DecimalField(decimal_places=17, max_digits=22)),
                ('distance_metres', models.IntegerField(help_text='Distance en mètres par rapport au centre du bureau')),
                ('timestamp_alerte', models.DateTimeField(auto_now_add=True)),
                ('heure_detection', models.TimeField(auto_now_add=True)),
                ('date_detection', models.DateField(auto_now_add=True)),
                ('en_heures_travail', models.BooleanField(default=True, help_text="True si l'alerte s'est produite pendant les heures de travail")),
                ('message_alerte', models.TextField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('active', 'Active'), ('resolue', 'Résolue'), ('ignoree', 'Ignorée')], default='active', max_length=20)),
                ('date_resolution', models.DateTimeField(blank=True, null=True)),
                ('commentaire_resolution', models.TextField(blank=True, null=True)),
                ('notification_envoyee', models.BooleanField(default=False)),
                ('notification_push_envoyee', models.BooleanField(default=False)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geofence_alerts', to=settings.AUTH_USER_MODEL)),
                ('bureau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geofence_alerts', to='core.bureau')),
                ('resolu_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='geofence_alerts_resolues', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Alerte de géofencing',
                'verbose_name_plural': 'Alertes de géofencing',
                'ordering': ['-timestamp_alerte'],
                'indexes': [models.Index(fields=['agent', 'date_detection'], name='core_geofen_agent_i_c7f270_idx'), models.Index(fields=['bureau', 'timestamp_alerte'], name='core_geofen_bureau__323a83_idx'), models.Index(fields=['statut', 'en_heures_travail'], name='core_geofen_statut_8bf385_idx')],
            },
        ),
        migrations.CreateModel(
            name='AgentLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=17, max_digits=22)),
                ('longitude', models.DecimalField(decimal_places=17, max_digits=22)),
                ('accuracy', models.FloatField(blank=True, help_text='Précision GPS en mètres', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_background', models.BooleanField(default=False, help_text='Position capturée en arrière-plan')),
                ('battery_level', models.IntegerField(blank=True, help_text='Niveau de batterie du téléphone', null=True)),
                ('distance_bureau', models.FloatField(blank=True, help_text='Distance calculée par rapport au bureau assigné', null=True)),
                ('dans_zone_autorisee', models.BooleanField(default=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Position agent',
                'verbose_name_plural': 'Positions agents',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['agent', 'timestamp'], name='core_agentl_agent_i_da2d87_idx'), models.Index(fields=['timestamp', 'dans_zone_autorisee'], name='core_agentl_timesta_e0ab00_idx')],
            },
        ),
    ]
