# Generated by Django 4.2.7 on 2025-10-01 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_geofencesettings_pushnotificationtoken_geofencealert_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pushnotificationtoken',
            name='token',
            field=models.CharField(help_text='Token FCM/APNS', max_length=255, unique=True),
        ),
    ]
