# Generated by Django 4.2.7 on 2025-10-02 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_alter_pushnotificationtoken_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='presence',
            name='heure_sortie',
            field=models.TimeField(blank=True, help_text='Heure de sortie automatique (éloignement > 200m)', null=True),
        ),
        migrations.AddField(
            model_name='presence',
            name='sortie_detectee',
            field=models.BooleanField(default=False, help_text='Sortie détectée par géolocalisation'),
        ),
        migrations.AddField(
            model_name='presence',
            name='statut_modifiable',
            field=models.BooleanField(default=True, help_text='Le statut peut être modifié par le supérieur'),
        ),
        migrations.AddField(
            model_name='presence',
            name='temps_absence_minutes',
            field=models.IntegerField(blank=True, help_text="Durée d'absence en minutes", null=True),
        ),
    ]
