# Generated by Django 4.2.7 on 2025-10-02 18:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_add_sortie_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['sous_direction__direction__nom', 'sous_direction__nom', 'nom'], 'verbose_name': 'Service', 'verbose_name_plural': 'Services'},
        ),
        migrations.AlterField(
            model_name='service',
            name='direction',
            field=models.ForeignKey(blank=True, help_text='DEPRECATED: Utilisez sous_direction à la place', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services_legacy', to='core.direction'),
        ),
        migrations.CreateModel(
            name='SousDirection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('direction', models.ForeignKey(help_text='La direction à laquelle cette sous-direction appartient', on_delete=django.db.models.deletion.CASCADE, related_name='sous_directions', to='core.direction')),
            ],
            options={
                'verbose_name': 'Sous-Direction',
                'verbose_name_plural': 'Sous-Directions',
                'ordering': ['direction__nom', 'nom'],
                'unique_together': {('nom', 'direction')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='service',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='service',
            name='sous_direction',
            field=models.ForeignKey(blank=True, help_text='La sous-direction à laquelle ce service appartient', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='core.sousdirection'),
        ),
        migrations.AlterUniqueTogether(
            name='service',
            unique_together={('nom', 'sous_direction')},
        ),
    ]
