# Generated by Django 4.2.7 on 2025-10-02 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_alter_service_options_alter_service_direction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolepermission',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('DIRECTEUR', 'Directeur'), ('SOUS_DIRECTEUR', 'Sous-Directeur'), ('CHEF_SERVICE', 'Chef de Service'), ('SUPERIEUR', 'Superieur'), ('AGENT', 'Agent'), ('SECRETAIRE', 'Secretaire'), ('PRESTATAIRE', 'Prestataire')], max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('DIRECTEUR', 'Directeur'), ('SOUS_DIRECTEUR', 'Sous-Directeur'), ('CHEF_SERVICE', 'Chef de Service'), ('SUPERIEUR', 'Superieur'), ('AGENT', 'Agent'), ('SECRETAIRE', 'Secretaire'), ('PRESTATAIRE', 'Prestataire')], default='AGENT', max_length=20),
        ),
    ]
