# Generated by Django 6.0.1 on 2026-01-27 22:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0100_add_rappel_traitement_to_courrier'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='bureau',
            name='latitude_centre',
            field=models.DecimalField(decimal_places=7, help_text='Latitude du centre du bureau', max_digits=10),
        ),
        migrations.AlterField(
            model_name='bureau',
            name='longitude_centre',
            field=models.DecimalField(decimal_places=7, help_text='Longitude du centre du bureau', max_digits=10),
        ),
        migrations.AlterField(
            model_name='geofencesettings',
            name='duree_minimale_hors_bureau_minutes',
            field=models.IntegerField(default=5, help_text='Durée minimale hors du bureau en minutes avant alerte'),
        ),
        migrations.CreateModel(
            name='CourrierRappel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_rappel', models.DateTimeField()),
                ('message', models.TextField()),
                ('envoye', models.BooleanField(default=False)),
                ('date_envoi', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('courrier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rappels', to='core.courrier')),
                ('cree_par', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rappels_crees', to=settings.AUTH_USER_MODEL)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rappels_courrier', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rappel Courrier',
                'verbose_name_plural': 'Rappels Courriers',
                'ordering': ['date_rappel'],
            },
        ),
        migrations.CreateModel(
            name='CourrierStatut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('nouveau', 'Nouveau'), ('en_cours', 'En cours de traitement'), ('traite', 'Traité'), ('archive', 'Archivé')], default='nouveau', max_length=20)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('date_modification', models.DateTimeField(auto_now_add=True)),
                ('courrier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique_statuts', to='core.courrier')),
                ('modifie_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modifications_courrier', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Statut Courrier',
                'verbose_name_plural': 'Statuts Courriers',
                'ordering': ['-date_modification'],
            },
        ),
        migrations.CreateModel(
            name='DeviceLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(db_index=True, help_text="Empreinte unique de l'appareil", max_length=255, unique=True)),
                ('username', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('locked_at', models.DateTimeField(auto_now_add=True)),
                ('last_used', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locked_devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Device Lock',
                'verbose_name_plural': 'Device Locks',
                'db_table': 'device_locks',
            },
        ),
        migrations.CreateModel(
            name='OccurrenceSpeciale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_occurrence', models.CharField(choices=[('REP1', 'Représentation demi-journée'), ('REP2', 'Représentation journée entière'), ('M1', "Mission à l'intérieur"), ('M2', "Mission à l'extérieur"), ('C', 'Congé'), ('T', 'Télétravail'), ('F', 'Férié'), ('P1', 'Permission demi-journée'), ('P2', 'Permission journée entière'), ('ABS', 'Absence non justifiée')], max_length=10)),
                ('nom_occurrence', models.CharField(max_length=100)),
                ('statut', models.CharField(choices=[('permission', 'Permission'), ('en mission', 'En mission'), ('congé', 'Congé'), ('télétravail', 'Télétravail'), ('férié', 'Férié'), ('absent', 'Absent')], max_length=32)),
                ('date', models.DateField(blank=True, help_text='Date unique (ancienne version)', null=True)),
                ('date_debut', models.DateField(blank=True, help_text="Date de début de l'occurrence", null=True)),
                ('date_fin', models.DateField(blank=True, help_text="Date de fin de l'occurrence", null=True)),
                ('heure_debut', models.TimeField(blank=True, help_text='Heure de début (pour demi-journée)', null=True)),
                ('heure_fin', models.TimeField(blank=True, help_text='Heure de fin (pour demi-journée)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occurrences_speciales', to=settings.AUTH_USER_MODEL)),
                ('createur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='occurrences_creees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Occurrence spéciale',
                'verbose_name_plural': 'Occurrences spéciales',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RendezVous',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objet', models.TextField(blank=True, default='', help_text='Objet du rendez-vous', null=True)),
                ('date_debut', models.DateTimeField(help_text='Début prévu')),
                ('date_fin', models.DateTimeField(help_text='Fin prévue')),
                ('lieu', models.CharField(blank=True, help_text='Salle ou bureau concerné', max_length=255, null=True)),
                ('visiteur_nom', models.CharField(blank=True, help_text='Nom du visiteur', max_length=255, null=True)),
                ('visiteur_prenoms', models.CharField(blank=True, help_text='Prénoms du visiteur', max_length=255, null=True)),
                ('visiteur_fonction', models.CharField(blank=True, help_text='Fonction du visiteur', max_length=255, null=True)),
                ('visiteur_telephone', models.CharField(blank=True, help_text='Téléphone du visiteur', max_length=50, null=True)),
                ('visiteur_type', models.CharField(blank=True, choices=[('ministere', 'Ministère'), ('entreprise', 'Entreprise'), ('particulier', 'Particulier')], help_text='Type de visiteur', max_length=20, null=True)),
                ('visiteur_structure', models.CharField(blank=True, help_text='Nom du ministère/entreprise ou autre précision', max_length=255, null=True)),
                ('statut', models.CharField(choices=[('prevu', 'Prévu'), ('en_cours', 'En cours'), ('effectue', 'Effectué'), ('annule', 'Annulé')], default='prevu', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organisateur', models.ForeignKey(help_text='Directeur ou responsable', on_delete=django.db.models.deletion.CASCADE, related_name='rendezvous_organises', to=settings.AUTH_USER_MODEL)),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rendezvous_assignes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rendez-vous',
                'verbose_name_plural': 'Rendez-vous',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='RendezVousDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(upload_to='rendezvous_documents/')),
                ('nom', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('rendezvous', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core.rendezvous')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document de rendez-vous',
                'verbose_name_plural': 'Documents de rendez-vous',
            },
        ),
        migrations.CreateModel(
            name='Reunion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intitule', models.CharField(help_text='Nom de la réunion', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Ordre du jour', null=True)),
                ('type_reunion', models.CharField(choices=[('presentiel', 'Présentiel'), ('en_ligne', 'En ligne'), ('mixte', 'Mixte')], default='presentiel', max_length=20)),
                ('date_debut', models.DateTimeField(help_text='Début de la réunion')),
                ('date_fin', models.DateTimeField(help_text='Fin de la réunion')),
                ('lieu', models.CharField(blank=True, help_text='Salle / lien Zoom', max_length=255, null=True)),
                ('lien_zoom', models.URLField(blank=True, help_text='Créé via API Zoom', null=True)),
                ('statut', models.CharField(choices=[('prevu', 'Prévu'), ('en_cours', 'En cours'), ('termine', 'Terminé'), ('annule', 'Annulé')], default='prevu', max_length=20)),
                ('compte_rendu', models.TextField(blank=True, help_text='Résumé de la réunion', null=True)),
                ('pv_fichier', models.FileField(blank=True, help_text='Procès-verbal uploadé', null=True, upload_to='reunions_pv/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organisateur', models.ForeignKey(help_text='Directeur ou sous-directeur', on_delete=django.db.models.deletion.CASCADE, related_name='reunions_organisees', to=settings.AUTH_USER_MODEL)),
                ('participants', models.ManyToManyField(blank=True, help_text='Liste des agents invités', related_name='reunions_participant', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Réunion',
                'verbose_name_plural': 'Réunions',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='CourrierNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_notification', models.CharField(choices=[('nouveau_courrier', 'Nouveau courrier reçu'), ('courrier_impute', 'Courrier imputé'), ('acces_accorde', 'Accès accordé'), ('acces_revoque', 'Accès révoqué'), ('rappel_traitement', 'Rappel de traitement'), ('statut_modifie', 'Statut modifié'), ('diligence_creee', 'Diligence créée'), ('commentaire_ajoute', 'Commentaire ajouté')], max_length=30)),
                ('titre', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('priorite', models.CharField(choices=[('basse', 'Basse'), ('normale', 'Normale'), ('haute', 'Haute'), ('urgente', 'Urgente')], default='normale', max_length=20)),
                ('lue', models.BooleanField(default=False)),
                ('date_lecture', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('courrier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='core.courrier')),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications_courrier_creees', to=settings.AUTH_USER_MODEL)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications_courrier', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification Courrier',
                'verbose_name_plural': 'Notifications Courriers',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['utilisateur', 'lue'], name='core_courri_utilisa_9d6e0e_idx'), models.Index(fields=['courrier'], name='core_courri_courrie_095452_idx'), models.Index(fields=['-created_at'], name='core_courri_created_71fbe3_idx')],
            },
        ),
        migrations.CreateModel(
            name='ReunionPresence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('present', models.BooleanField(default=False)),
                ('heure_arrivee', models.TimeField(blank=True, null=True)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('reunion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presences', to='core.reunion')),
            ],
            options={
                'verbose_name': 'Présence à une réunion',
                'verbose_name_plural': 'Présences aux réunions',
                'unique_together': {('reunion', 'participant')},
            },
        ),
    ]
