# Generated by Django 6.0.5 on 2026-05-07 17:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0103_fix_reunion_organisateur_related_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorieDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('icone', models.CharField(blank=True, max_length=50, null=True)),
                ('duree_conservation_ans', models.PositiveIntegerField(blank=True, help_text='Durée légale de conservation en années (ex: 10)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sous_categories', to='core.categoriedocument')),
            ],
            options={
                'verbose_name': 'Catégorie de document',
                'verbose_name_plural': 'Catégories de documents',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, max_length=100, unique=True)),
                ('titre', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True, null=True)),
                ('fichier', models.FileField(upload_to='ged/documents/%Y/%m/')),
                ('type_fichier', models.CharField(choices=[('pdf', 'PDF'), ('word', 'Word'), ('excel', 'Excel'), ('image', 'Image'), ('scan', 'Scan'), ('autre', 'Autre')], default='pdf', max_length=20)),
                ('taille_fichier', models.BigIntegerField(default=0, help_text='Taille en octets')),
                ('nom_fichier_original', models.CharField(blank=True, max_length=255)),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('en_validation', 'En validation'), ('valide', 'Validé'), ('signe', 'Signé'), ('diffuse', 'Diffusé'), ('archive', 'Archivé')], default='brouillon', max_length=20)),
                ('confidentialite', models.CharField(choices=[('public', 'Public'), ('interne', 'Interne'), ('confidentiel', 'Confidentiel')], default='interne', max_length=20)),
                ('mots_cles', models.TextField(blank=True, help_text='Mots-clés séparés par des virgules', null=True)),
                ('contenu_ocr', models.TextField(blank=True, help_text='Texte extrait par OCR', null=True)),
                ('date_document', models.DateField(blank=True, null=True)),
                ('date_expiration', models.DateField(blank=True, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('est_version_courante', models.BooleanField(default=True)),
                ('archive_le', models.DateTimeField(blank=True, null=True)),
                ('duree_conservation_ans', models.PositiveIntegerField(blank=True, null=True)),
                ('date_destruction_prevue', models.DateField(blank=True, null=True)),
                ('hash_sha256', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archive_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ged_documents_archives', to=settings.AUTH_USER_MODEL)),
                ('auteur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ged_documents_crees', to=settings.AUTH_USER_MODEL)),
                ('categorie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='core.categoriedocument')),
                ('courrier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ged_documents', to='core.courrier')),
                ('diligence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ged_documents', to='core.diligence')),
                ('document_original', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versions_precedentes', to='core.document')),
                ('reunion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ged_documents', to='core.reunion')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ged_documents', to='core.service')),
                ('tache', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ged_documents', to='core.tache')),
            ],
            options={
                'verbose_name': 'Document GED',
                'verbose_name_plural': 'Documents GED',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CertificatArchivage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_certificat', models.CharField(max_length=50, unique=True)),
                ('hash_sha256', models.CharField(max_length=64)),
                ('horodatage', models.DateTimeField(auto_now_add=True)),
                ('valide', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('auteur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificats_emis', to=settings.AUTH_USER_MODEL)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certificat_archivage', to='core.document')),
            ],
            options={
                'verbose_name': "Certificat d'archivage",
                'verbose_name_plural': "Certificats d'archivage",
            },
        ),
        migrations.CreateModel(
            name='DocumentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('creation', 'Création'), ('modification', 'Modification'), ('consultation', 'Consultation'), ('telechargement', 'Téléchargement'), ('validation', 'Validation'), ('archivage', 'Archivage'), ('nouvelle_version', 'Nouvelle version'), ('acces_refuse', 'Accès refusé')], max_length=20)),
                ('details', models.TextField(blank=True, null=True)),
                ('adresse_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='core.document')),
                ('utilisateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Journal document',
                'verbose_name_plural': 'Journal documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('droit', models.CharField(choices=[('lecture', 'Lecture'), ('modification', 'Modification'), ('validation', 'Validation'), ('archivage', 'Archivage')], default='lecture', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accorde_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ged_acces_accordes', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acces', to='core.document')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ged_acces', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Accès document',
                'verbose_name_plural': 'Accès documents',
                'unique_together': {('document', 'user', 'droit')},
            },
        ),
        migrations.CreateModel(
            name='DocumentVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_version', models.PositiveIntegerField()),
                ('fichier', models.FileField(upload_to='ged/versions/%Y/%m/')),
                ('nom_fichier_original', models.CharField(blank=True, max_length=255)),
                ('hash_sha256', models.CharField(blank=True, max_length=64)),
                ('taille_fichier', models.BigIntegerField(default=0)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('auteur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique_versions', to='core.document')),
            ],
            options={
                'verbose_name': 'Version de document',
                'verbose_name_plural': 'Versions de documents',
                'ordering': ['-numero_version'],
                'unique_together': {('document', 'numero_version')},
            },
        ),
    ]
