# Generated by Django 5.2.10 on 2026-05-09 00:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0104_ged_archivage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentRH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_document', models.CharField(choices=[('arrete', 'Arrêté'), ('decision', 'Décision'), ('affectation', 'Affectation'), ('promotion', 'Promotion'), ('sanction', 'Sanction'), ('acte', 'Acte administratif'), ('contrat', 'Contrat'), ('diplome', 'Diplôme'), ('autre', 'Autre')], max_length=20)),
                ('titre', models.CharField(max_length=500)),
                ('reference', models.CharField(blank=True, max_length=200)),
                ('date_document', models.DateField()),
                ('fichier', models.FileField(blank=True, null=True, upload_to='rh/documents/')),
                ('description', models.TextField(blank=True)),
                ('signataire', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents_rh', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_rh_crees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document RH',
                'ordering': ['-date_document'],
            },
        ),
        migrations.CreateModel(
            name='EvaluationRH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.PositiveIntegerField()),
                ('periode', models.CharField(blank=True, default='Annuelle', max_length=50)),
                ('note_globale', models.FloatField(default=0)),
                ('mention', models.CharField(blank=True, choices=[('excellent', 'Excellent'), ('tres_bien', 'Très Bien'), ('bien', 'Bien'), ('satisfaisant', 'Satisfaisant'), ('insuffisant', 'Insuffisant')], max_length=20)),
                ('ponctualite', models.FloatField(default=0)),
                ('assiduite', models.FloatField(default=0)),
                ('competence', models.FloatField(default=0)),
                ('initiative', models.FloatField(default=0)),
                ('travail_equipe', models.FloatField(default=0)),
                ('rendement', models.FloatField(default=0)),
                ('appreciation', models.TextField(blank=True)),
                ('objectifs_atteints', models.TextField(blank=True)),
                ('objectifs_prochaine_periode', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations_rh', to=settings.AUTH_USER_MODEL)),
                ('evaluateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluations_rh_faites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Évaluation RH',
                'ordering': ['-annee'],
            },
        ),
        migrations.CreateModel(
            name='FicheAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=50, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('prenoms', models.CharField(max_length=200)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='rh/agents/photos/')),
                ('grade', models.CharField(blank=True, max_length=100)),
                ('emploi', models.CharField(blank=True, max_length=200)),
                ('fonction', models.CharField(blank=True, max_length=200)),
                ('date_prise_service', models.DateField(blank=True, null=True)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('lieu_naissance', models.CharField(blank=True, max_length=200)),
                ('situation_matrimoniale', models.CharField(choices=[('celibataire', 'Célibataire'), ('marie', 'Marié(e)'), ('divorce', 'Divorcé(e)'), ('veuf', 'Veuf/Veuve')], default='celibataire', max_length=20)),
                ('nombre_enfants', models.PositiveIntegerField(default=0)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('email_professionnel', models.EmailField(blank=True, max_length=254)),
                ('adresse', models.TextField(blank=True)),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('suspendu', 'Suspendu'), ('retraite', 'Retraité'), ('demissionnaire', 'Démissionnaire')], default='actif', max_length=20)),
                ('contact_urgence_nom', models.CharField(blank=True, max_length=200)),
                ('contact_urgence_tel', models.CharField(blank=True, max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('direction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fiches_agents', to='core.direction')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fiches_agents', to='core.service')),
                ('sous_direction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fiches_agents', to='core.sousdirection')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fiche_agent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Fiche Agent',
                'ordering': ['nom', 'prenoms'],
            },
        ),
        migrations.CreateModel(
            name='FormationRH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('organisateur', models.CharField(blank=True, max_length=500)),
                ('lieu', models.CharField(blank=True, max_length=500)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('duree_heures', models.PositiveIntegerField(default=0)),
                ('statut', models.CharField(choices=[('planifiee', 'Planifiée'), ('en_cours', 'En cours'), ('terminee', 'Terminée'), ('annulee', 'Annulée')], default='planifiee', max_length=20)),
                ('places_disponibles', models.PositiveIntegerField(blank=True, null=True)),
                ('cout', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='formations_rh_creees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Formation RH',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='MissionRH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objet', models.CharField(max_length=500)),
                ('destination', models.CharField(max_length=500)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('vehicule', models.BooleanField(default=False)),
                ('type_vehicule', models.CharField(blank=True, max_length=100)),
                ('frais_alloues', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('ordre_mission_num', models.CharField(blank=True, max_length=100)),
                ('statut', models.CharField(choices=[('demande', 'Demande'), ('validee', 'Validée'), ('rejetee', 'Rejetée'), ('en_cours', 'En cours'), ('terminee', 'Terminée'), ('archivee', 'Archivée')], default='demande', max_length=20)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('motif_rejet', models.TextField(blank=True)),
                ('rapport', models.TextField(blank=True)),
                ('rapport_fichier', models.FileField(blank=True, null=True, upload_to='rh/missions/rapports/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missions_rh', to=settings.AUTH_USER_MODEL)),
                ('valideur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='missions_rh_validees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mission RH',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InscriptionFormationRH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('inscrit', 'Inscrit'), ('present', 'Présent'), ('absent', 'Absent'), ('certifie', 'Certifié')], default='inscrit', max_length=20)),
                ('attestation', models.FileField(blank=True, null=True, upload_to='rh/formations/attestations/')),
                ('note', models.FloatField(blank=True, null=True)),
                ('observations', models.TextField(blank=True)),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions_formations_rh', to=settings.AUTH_USER_MODEL)),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='core.formationrh')),
            ],
            options={
                'unique_together': {('formation', 'agent')},
            },
        ),
    ]
