# Generated by Django 5.2.10 on 2026-05-09 04:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0105_rh_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='sous_direction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile_users', to='core.sousdirection'),
        ),
    ]
