# Generated by Django 5.2.10 on 2026-05-09 15:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0107_add_direction_to_userprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeAttestation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_attestation', models.CharField(choices=[('travail', 'Attestation de travail'), ('presence', 'Attestation de présence')], max_length=20)),
                ('motif', models.TextField(blank=True)),
                ('nombre_copies', models.PositiveIntegerField(default=1)),
                ('commentaire_agent', models.TextField(blank=True)),
                ('date_souhaitee', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('en_cours', 'En cours de traitement'), ('traitee', 'Traitée'), ('terminee', 'Terminée'), ('rejetee', 'Rejetée'), ('annulee', 'Annulée')], default='en_attente', max_length=20)),
                ('commentaire_rh', models.TextField(blank=True)),
                ('numero_attestation', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='attestations/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_attestations', to=settings.AUTH_USER_MODEL)),
                ('responsable_rh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attestations_traitees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Demande d'attestation",
                'verbose_name_plural': "Demandes d'attestation",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('type_site', models.CharField(choices=[('siege', 'Siège'), ('direction_regionale', 'Direction Régionale'), ('agence', 'Agence'), ('antenne', 'Antenne')], default='siege', max_length=30)),
                ('adresse', models.CharField(blank=True, max_length=500)),
                ('ville', models.CharField(blank=True, max_length=100)),
                ('commune', models.CharField(blank=True, max_length=100)),
                ('telephone', models.CharField(blank=True, max_length=32)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='sites/logos/')),
                ('fuseau_horaire', models.CharField(default='Africa/Abidjan', max_length=50)),
                ('est_actif', models.BooleanField(default=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('rayon_pointage', models.IntegerField(default=200, help_text='Rayon en mètres pour le pointage GPS')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sites_responsable', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Site',
                'verbose_name_plural': 'Sites',
                'ordering': ['nom'],
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agents', to='core.site'),
        ),
    ]
