# Generated by Django 6.0.5 on 2026-05-11 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0108_multi_site_attestation'),
    ]

    operations = [
        migrations.CreateModel(
            name='SitePalier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Ex: Rez-de-chaussée, 3ème étage, Bâtiment B', max_length=100)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('rayon_pointage', models.IntegerField(default=200, help_text='Rayon en mètres pour le pointage GPS')),
                ('est_actif', models.BooleanField(default=True)),
                ('ordre', models.PositiveSmallIntegerField(default=0, help_text="Ordre d'affichage")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paliers', to='core.site')),
            ],
            options={
                'verbose_name': 'Palier de site',
                'verbose_name_plural': 'Paliers de site',
                'ordering': ['ordre', 'nom'],
            },
        ),
    ]
