# Generated by Django 6.0.5 on 2026-06-24 16:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0110_site_org_unit_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='courrier',
            name='commentaires',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='CourrierInstruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instructions', models.JSONField(default=list, help_text="Liste des codes d'instructions sélectionnées")),
                ('date_limite_reaction', models.DateField(blank=True, null=True)),
                ('commentaire', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('courrier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courrier_instructions', to='core.courrier')),
                ('creee_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instructions_creees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Instruction Courrier',
                'verbose_name_plural': 'Instructions Courrier',
                'ordering': ['-created_at'],
            },
        ),
    ]
