# Generated by Django 6.0.5 on 2026-06-24 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0111_add_courrier_instruction_and_ref_gen'),
    ]

    operations = [
        migrations.AddField(
            model_name='courrier',
            name='mots_cles',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='courrier',
            name='niveau_urgence',
            field=models.CharField(blank=True, choices=[('faible', 'Faible'), ('normal', 'Normal'), ('haute', 'Haute'), ('critique', 'Critique')], default='normal', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='courrier',
            name='ocr_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='courrier',
            name='resume_ia',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='courrier',
            name='service_propose',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='courrier',
            name='theme',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='courrier',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='courriers/thumbnails/'),
        ),
        migrations.AddField(
            model_name='courrier',
            name='traitement_statut',
            field=models.CharField(blank=True, choices=[('en_attente', 'En attente'), ('en_cours', 'En cours'), ('termine', 'Terminé'), ('erreur', 'Erreur')], default='en_attente', max_length=20, null=True),
        ),
    ]
