# Generated by Django 6.0.5 on 2026-08-07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0116_courrierannexe'),
    ]

    operations = [
        migrations.AddField(
            model_name='presence',
            name='local_id',
            field=models.UUIDField(blank=True, help_text="Identifiant genere par l'app mobile pour deduplier une resynchronisation hors-ligne", null=True, unique=True),
        ),
        migrations.AddField(
            model_name='presence',
            name='captured_at',
            field=models.DateTimeField(blank=True, help_text="Horodatage reel de capture du pointage sur l'appareil (peut preceder created_at en cas de synchronisation differee)", null=True),
        ),
        migrations.AddField(
            model_name='agentlocation',
            name='local_id',
            field=models.UUIDField(blank=True, help_text="Identifiant genere par l'app mobile pour deduplier un ping GPS resynchronise", null=True, unique=True),
        ),
        migrations.AddField(
            model_name='agentlocation',
            name='captured_at',
            field=models.DateTimeField(blank=True, help_text="Horodatage reel de capture de la position sur l'appareil (peut preceder timestamp en cas de synchronisation differee)", null=True),
        ),
    ]
