# Generated by Django 5.2.15 on 2026-08-14 21:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0118_seed_dynamic_module_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeDestruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motif', models.TextField(blank=True)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('APPROUVEE', 'Approuvée'), ('REJETEE', 'Rejetée'), ('EXECUTEE', 'Exécutée')], default='EN_ATTENTE', max_length=20)),
                ('motif_decision', models.TextField(blank=True)),
                ('date_demande', models.DateTimeField(auto_now_add=True)),
                ('date_decision', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Demande de destruction',
                'verbose_name_plural': 'Demandes de destruction',
                'ordering': ['-date_demande'],
            },
        ),
        migrations.CreateModel(
            name='DocumentShareLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('expire_le', models.DateTimeField(blank=True, null=True)),
                ('mot_de_passe_hash', models.CharField(blank=True, max_length=255)),
                ('nombre_acces', models.PositiveIntegerField(default=0)),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Lien de partage document',
                'verbose_name_plural': 'Liens de partage documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='document',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ged_documents', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='document',
            name='est_supprime',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='document',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='supprime_le',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='supprime_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ged_documents_supprimes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='documentlog',
            name='action',
            field=models.CharField(choices=[('creation', 'Création'), ('modification', 'Modification'), ('consultation', 'Consultation'), ('telechargement', 'Téléchargement'), ('validation', 'Validation'), ('archivage', 'Archivage'), ('nouvelle_version', 'Nouvelle version'), ('acces_refuse', 'Accès refusé'), ('suppression', 'Envoyé à la corbeille'), ('restauration', 'Restauré depuis la corbeille'), ('partage_cree', 'Lien de partage créé'), ('partage_revoque', 'Lien de partage révoqué'), ('partage_consulte', 'Consulté via lien de partage'), ('partage_telecharge', 'Téléchargé via lien de partage'), ('destruction_demandee', 'Destruction demandée'), ('destruction_approuvee', 'Destruction approuvée'), ('destruction_rejetee', 'Destruction rejetée'), ('extraction_texte', 'Texte extrait (recherche)')], max_length=25),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['content_type', 'object_id'], name='core_docume_content_343c2e_idx'),
        ),
        migrations.AddField(
            model_name='demandedestruction',
            name='decide_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ged_destructions_decidees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='demandedestruction',
            name='demande_par',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ged_destructions_demandees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='demandedestruction',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_destruction', to='core.document'),
        ),
        migrations.AddField(
            model_name='documentsharelink',
            name='cree_par',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ged_liens_crees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documentsharelink',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liens_partage', to='core.document'),
        ),
    ]
