# Generated by Django 5.2.15 on 2026-08-16 09:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0119_demandedestruction_documentsharelink_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='presence',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='presence',
            name='enregistre_par',
            field=models.ForeignKey(blank=True, help_text='Utilisateur ayant effectue la saisie (secretaire/accueil) ; vide pour un auto-pointage', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presences_enregistrees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='presence',
            name='fiche_agent',
            field=models.ForeignKey(blank=True, help_text='Fiche agent RH ciblee par un pointage assiste (sans ligne Agent correspondante)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presences', to='core.ficheagent'),
        ),
        migrations.AddField(
            model_name='presence',
            name='liveness_method',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='presence',
            name='liveness_passed',
            field=models.BooleanField(blank=True, help_text='Null = non applicable (auto-pointage ou pointage assiste sans photo)', null=True),
        ),
        migrations.AddField(
            model_name='presence',
            name='reference_photo_absente',
            field=models.BooleanField(default=False, help_text="Vrai si la FicheAgent n'avait pas de photo de reference au moment du pointage"),
        ),
        migrations.AddField(
            model_name='presence',
            name='verification_method',
            field=models.CharField(choices=[('self', 'Auto-pointage'), ('proxy_facial', 'Assiste — verification faciale'), ('proxy_manual', 'Assiste — sans photo')], default='self', max_length=20),
        ),
        migrations.AddField(
            model_name='presence',
            name='verification_photo',
            field=models.ImageField(blank=True, null=True, upload_to='presences/verification/'),
        ),
        migrations.AlterField(
            model_name='presence',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='presences', to='core.agent'),
        ),
        migrations.AddConstraint(
            model_name='presence',
            constraint=models.UniqueConstraint(condition=models.Q(('agent__isnull', False)), fields=('agent', 'date_presence'), name='uniq_presence_agent_date'),
        ),
        migrations.AddConstraint(
            model_name='presence',
            constraint=models.UniqueConstraint(condition=models.Q(('fiche_agent__isnull', False)), fields=('fiche_agent', 'date_presence'), name='uniq_presence_ficheagent_date'),
        ),
    ]
