# Generated by Django 5.2.15 on 2026-08-16 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0120_alter_presence_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='presence',
            name='face_match_distance',
            field=models.FloatField(blank=True, help_text='Distance faciale (face_recognition) entre la photo de reference et la photo capturee — plus bas = plus proche. Null si comparaison non effectuee (pas de photo de reference ou moteur indisponible).', null=True),
        ),
    ]
