# Generated by Django 5.2.15 on 2026-08-17 22:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0121_presence_face_match_distance'),
    ]

    operations = [
        migrations.AddField(
            model_name='direction',
            name='parent_direction',
            field=models.ForeignKey(blank=True, help_text='Direction parente, pour un rattachement hierarchique entre directions (ex: Direction sous Direction Generale/Cabinet).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='directions_filles', to='core.direction'),
        ),
    ]
