# Generated by Django 6.0.5 on 2026-09-03 21:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0122_direction_parent_direction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Création'), ('update', 'Modification'), ('delete', 'Suppression'), ('password_change', 'Changement de mot de passe')], max_length=20)),
                ('target_username', models.CharField(blank=True, max_length=150)),
                ('acting_username', models.CharField(blank=True, max_length=150)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=400)),
                ('changes', models.JSONField(blank=True, default=dict, help_text='Données envoyées / champs modifiés (mot de passe masqué).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('acting_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs_as_actor', to=settings.AUTH_USER_MODEL)),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs_as_target', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Journal d'audit utilisateur",
                'verbose_name_plural': "Journaux d'audit utilisateurs",
                'ordering': ['-created_at'],
            },
        ),
    ]
