# Generated by Django 6.0.5 on 2026-09-30 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0123_userauditlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presence',
            name='verification_photo',
        ),
    ]
