# Generated by Django 6.0.5 on 2026-09-30 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0124_remove_presence_verification_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='ficheagent',
            name='face_encoding',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
