# Generated by Django 5.2.10 on 2026-05-06 12:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0101_alter_bureau_latitude_centre_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255, verbose_name='Titre du projet')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('objectifs', models.TextField(blank=True, default='', verbose_name='Objectifs')),
                ('date_debut', models.DateField(verbose_name='Date de début')),
                ('date_fin_prevue', models.DateField(verbose_name='Date de fin prévue')),
                ('date_fin_effective', models.DateField(blank=True, null=True, verbose_name='Date de fin effective')),
                ('budget_prevu', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Budget prévu')),
                ('budget_consomme', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Budget consommé')),
                ('statut', models.CharField(choices=[('planifie', 'Planifié'), ('en_cours', 'En cours'), ('termine', 'Terminé'), ('en_retard', 'En retard'), ('suspendu', 'Suspendu')], default='planifie', max_length=20, verbose_name='Statut')),
                ('pourcentage_avancement', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Avancement (%)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('courrier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projets_lies', to='core.courrier', verbose_name='Courrier lié')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projets_crees', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('diligence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projets_lies', to='core.diligence', verbose_name='Diligence liée')),
                ('direction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projets_module', to='core.direction', verbose_name='Direction')),
                ('equipe', models.ManyToManyField(blank=True, related_name='projets_equipe', to=settings.AUTH_USER_MODEL, verbose_name='Équipe projet')),
                ('responsable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projets_geres', to=settings.AUTH_USER_MODEL, verbose_name='Responsable principal')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projets_module', to='core.service', verbose_name='Service')),
            ],
            options={
                'verbose_name': 'Projet',
                'verbose_name_plural': 'Projets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Tache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255, verbose_name='Titre')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('date_debut', models.DateField(blank=True, null=True, verbose_name='Date de début')),
                ('date_fin_prevue', models.DateField(blank=True, null=True, verbose_name='Date de fin prévue')),
                ('date_fin_effective', models.DateField(blank=True, null=True, verbose_name='Date de fin effective')),
                ('priorite', models.CharField(choices=[('haute', 'Haute'), ('moyenne', 'Moyenne'), ('basse', 'Basse')], default='moyenne', max_length=10, verbose_name='Priorité')),
                ('statut', models.CharField(choices=[('a_faire', 'À faire'), ('en_cours', 'En cours'), ('termine', 'Terminé')], default='a_faire', max_length=10, verbose_name='Statut')),
                ('pourcentage_avancement', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Avancement (%)')),
                ('poids', models.PositiveIntegerField(default=1, verbose_name='Poids (pondération)')),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agents_assignes', models.ManyToManyField(blank=True, related_name='projet_taches_assignees', to=settings.AUTH_USER_MODEL, verbose_name='Agents assignés')),
                ('courrier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taches_projet_liees', to='core.courrier', verbose_name='Courrier lié')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projet_taches_creees', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('diligence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taches_projet_liees', to='core.diligence', verbose_name='Diligence liée')),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taches', to='projet.projet', verbose_name='Projet')),
                ('responsable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projet_taches_responsable', to=settings.AUTH_USER_MODEL, verbose_name='Responsable')),
                ('tache_dependante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taches_dependantes', to='projet.tache', verbose_name='Dépend de')),
            ],
            options={
                'verbose_name': 'Tâche',
                'verbose_name_plural': 'Tâches',
                'ordering': ['ordre', '-priorite', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SousTache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255, verbose_name='Titre')),
                ('date_echeance', models.DateField(blank=True, null=True, verbose_name='Échéance')),
                ('statut', models.CharField(choices=[('a_faire', 'À faire'), ('en_cours', 'En cours'), ('termine', 'Terminé')], default='a_faire', max_length=10, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projet_sous_taches', to=settings.AUTH_USER_MODEL, verbose_name='Responsable')),
                ('tache', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sous_taches', to='projet.tache', verbose_name='Tâche parent')),
            ],
            options={
                'verbose_name': 'Sous-tâche',
                'verbose_name_plural': 'Sous-tâches',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='PieceJointe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(upload_to='projet/pieces_jointes/%Y/%m/', verbose_name='Fichier')),
                ('nom', models.CharField(max_length=255, verbose_name='Nom du fichier')),
                ('type_fichier', models.CharField(blank=True, default='', max_length=100, verbose_name='Type')),
                ('taille', models.PositiveIntegerField(default=0, verbose_name='Taille (octets)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projet_fichiers_uploades', to=settings.AUTH_USER_MODEL, verbose_name='Uploadé par')),
                ('projet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pieces_jointes', to='projet.projet', verbose_name='Projet')),
                ('tache', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pieces_jointes', to='projet.tache', verbose_name='Tâche')),
            ],
            options={
                'verbose_name': 'Pièce jointe',
                'verbose_name_plural': 'Pièces jointes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationProjet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_notification', models.CharField(choices=[('creation_tache', 'Création de tâche'), ('modification_tache', 'Modification de tâche'), ('retard_detecte', 'Retard détecté'), ('commentaire_ajoute', 'Commentaire ajouté'), ('rappel_echeance', 'Rappel avant échéance'), ('tache_terminee', 'Tâche terminée'), ('projet_termine', 'Projet terminé'), ('livrable_soumis', 'Livrable soumis'), ('livrable_valide', 'Livrable validé'), ('livrable_rejete', 'Livrable rejeté'), ('assignation', 'Assignation'), ('validation_requise', 'Validation requise')], max_length=30, verbose_name='Type')),
                ('titre', models.CharField(max_length=255, verbose_name='Titre')),
                ('message', models.TextField(verbose_name='Message')),
                ('lue', models.BooleanField(default=False, verbose_name='Lue')),
                ('date_lecture', models.DateTimeField(blank=True, null=True, verbose_name='Date de lecture')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Données supplémentaires')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications_projet', to=settings.AUTH_USER_MODEL, verbose_name='Destinataire')),
                ('projet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='projet.projet', verbose_name='Projet')),
                ('tache', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='projet.tache', verbose_name='Tâche')),
            ],
            options={
                'verbose_name': 'Notification Projet',
                'verbose_name_plural': 'Notifications Projet',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Livrable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255, verbose_name='Titre')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('fichier', models.FileField(upload_to='projet/livrables/%Y/%m/', verbose_name='Fichier')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='Version')),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('soumis', 'Soumis'), ('valide', 'Validé'), ('rejete', 'Rejeté')], default='brouillon', max_length=10, verbose_name='Statut')),
                ('commentaire_validation', models.TextField(blank=True, default='', verbose_name='Commentaire de validation')),
                ('date_validation', models.DateTimeField(blank=True, null=True, verbose_name='Date de validation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('soumis_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='livrables_soumis', to=settings.AUTH_USER_MODEL, verbose_name='Soumis par')),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='livrables_valides', to=settings.AUTH_USER_MODEL, verbose_name='Validé par')),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livrables', to='projet.projet', verbose_name='Projet')),
                ('tache', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='livrables', to='projet.tache', verbose_name='Tâche associée')),
            ],
            options={
                'verbose_name': 'Livrable',
                'verbose_name_plural': 'Livrables',
                'ordering': ['-version', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HistoriqueAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('creation', 'Création'), ('modification', 'Modification'), ('suppression', 'Suppression'), ('changement_statut', 'Changement de statut'), ('assignation', 'Assignation'), ('commentaire', 'Commentaire'), ('upload', 'Upload de fichier'), ('validation', 'Validation'), ('livrable', 'Action sur livrable')], max_length=30, verbose_name='Action')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='Détails')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projet_historique_actions', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
                ('projet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='historique', to='projet.projet', verbose_name='Projet')),
                ('tache', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='historique', to='projet.tache', verbose_name='Tâche')),
            ],
            options={
                'verbose_name': "Historique d'action",
                'verbose_name_plural': "Historiques d'actions",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommentaireTache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField(verbose_name='Contenu')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projet_commentaires', to=settings.AUTH_USER_MODEL, verbose_name='Auteur')),
                ('tache', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentaires', to='projet.tache', verbose_name='Tâche')),
            ],
            options={
                'verbose_name': 'Commentaire',
                'verbose_name_plural': 'Commentaires',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ValidationTache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('soumise', 'Soumise'), ('validee', 'Validée'), ('rejetee', 'Rejetée')], default='soumise', max_length=10, verbose_name='Statut')),
                ('commentaire', models.TextField(blank=True, default='', verbose_name='Commentaire')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('soumis_par', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validations_soumises', to=settings.AUTH_USER_MODEL, verbose_name='Soumis par')),
                ('tache', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validations', to='projet.tache', verbose_name='Tâche')),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validations_traitees', to=settings.AUTH_USER_MODEL, verbose_name='Traité par')),
            ],
            options={
                'verbose_name': 'Validation de tâche',
                'verbose_name_plural': 'Validations de tâches',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='projet',
            index=models.Index(fields=['statut'], name='projet_proj_statut_9e89b4_idx'),
        ),
        migrations.AddIndex(
            model_name='projet',
            index=models.Index(fields=['responsable'], name='projet_proj_respons_73e946_idx'),
        ),
        migrations.AddIndex(
            model_name='projet',
            index=models.Index(fields=['-created_at'], name='projet_proj_created_db26d7_idx'),
        ),
        migrations.AddIndex(
            model_name='tache',
            index=models.Index(fields=['statut'], name='projet_tach_statut_c594b3_idx'),
        ),
        migrations.AddIndex(
            model_name='tache',
            index=models.Index(fields=['projet', 'statut'], name='projet_tach_projet__2ad930_idx'),
        ),
        migrations.AddIndex(
            model_name='tache',
            index=models.Index(fields=['responsable'], name='projet_tach_respons_6660bd_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationprojet',
            index=models.Index(fields=['user', 'lue'], name='projet_noti_user_id_a82087_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationprojet',
            index=models.Index(fields=['-created_at'], name='projet_noti_created_b4dc57_idx'),
        ),
        migrations.AddIndex(
            model_name='historiqueaction',
            index=models.Index(fields=['-created_at'], name='projet_hist_created_a12381_idx'),
        ),
        migrations.AddIndex(
            model_name='historiqueaction',
            index=models.Index(fields=['projet'], name='projet_hist_projet__bcc580_idx'),
        ),
        migrations.AddIndex(
            model_name='historiqueaction',
            index=models.Index(fields=['tache'], name='projet_hist_tache_i_4fbe6f_idx'),
        ),
    ]
