# Generated by Django 6.0.5 on 2026-05-08 23:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projet', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReunionProjet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255, verbose_name='Titre')),
                ('type_reunion', models.CharField(choices=[('reunion_suivi', 'Réunion de suivi'), ('rendez_vous', 'Rendez-vous'), ('point_avancement', "Point d'avancement"), ('comite_pilotage', 'Comité de pilotage')], default='reunion_suivi', max_length=20, verbose_name='Type')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description / Ordre du jour')),
                ('lieu', models.CharField(blank=True, default='', max_length=255, verbose_name='Lieu')),
                ('lien_visio', models.URLField(blank=True, default='', verbose_name='Lien visioconférence')),
                ('date', models.DateField(verbose_name='Date')),
                ('heure_debut', models.TimeField(verbose_name='Heure de début')),
                ('heure_fin', models.TimeField(blank=True, null=True, verbose_name='Heure de fin')),
                ('statut', models.CharField(choices=[('planifie', 'Planifié'), ('en_cours', 'En cours'), ('termine', 'Terminé'), ('annule', 'Annulé')], default='planifie', max_length=10, verbose_name='Statut')),
                ('compte_rendu', models.TextField(blank=True, default='', verbose_name='Compte rendu')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organisateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reunions_organisees', to=settings.AUTH_USER_MODEL, verbose_name='Organisateur')),
                ('participants', models.ManyToManyField(blank=True, related_name='reunions_invitees', to=settings.AUTH_USER_MODEL, verbose_name='Participants')),
                ('projet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reunions', to='projet.projet', verbose_name='Projet')),
                ('tache', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reunions', to='projet.tache', verbose_name='Tâche associée')),
            ],
            options={
                'verbose_name': 'Réunion',
                'verbose_name_plural': 'Réunions',
                'ordering': ['date', 'heure_debut'],
                'indexes': [models.Index(fields=['date'], name='projet_reun_date_a7e2af_idx'), models.Index(fields=['projet'], name='projet_reun_projet__66e3fa_idx')],
            },
        ),
    ]
