# Generated by Django 5.2.15 on 2026-08-14 11:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dfir_formations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscriptionparticipant',
            name='commentaire',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='inscriptionparticipant',
            name='date_evaluation',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inscriptionparticipant',
            name='note_formateur',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Note sur 5', null=True),
        ),
        migrations.AddField(
            model_name='inscriptionparticipant',
            name='note_session',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Note sur 5', null=True),
        ),
        migrations.AddField(
            model_name='inscriptionparticipant',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
