# Generated by Django 5.2.15 on 2026-08-14 16:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dfir_formations', '0002_inscriptionparticipant_commentaire_and_more'),
        ('dfir_participants', '0002_participantdfir_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificatFormation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50, unique=True)),
                ('code_verification', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('date_delivrance', models.DateTimeField(auto_now_add=True)),
                ('inscription', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certificat', to='dfir_formations.inscriptionparticipant')),
            ],
            options={
                'ordering': ['-date_delivrance'],
            },
        ),
        migrations.CreateModel(
            name='ClasseVirtuelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('provider', models.CharField(choices=[('GOOGLE_MEET', 'Google Meet'), ('TEAMS', 'Microsoft Teams'), ('ZOOM', 'Zoom'), ('AUTRE', 'Autre')], default='GOOGLE_MEET', max_length=15)),
                ('date_debut', models.DateTimeField()),
                ('date_fin', models.DateTimeField(blank=True, null=True)),
                ('join_url', models.URLField()),
                ('compte_rendu', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes_virtuelles', to='dfir_formations.sessionformation')),
            ],
            options={
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='Lecon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('type_contenu', models.CharField(choices=[('VIDEO', 'Vidéo'), ('DOCUMENT', 'Document'), ('TEXTE', 'Texte')], default='VIDEO', max_length=10)),
                ('url_contenu', models.URLField(blank=True, help_text='Lien vidéo, document ou ressource externe')),
                ('texte_contenu', models.TextField(blank=True, help_text='Contenu texte si type = TEXTE')),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('duree_minutes', models.PositiveIntegerField(default=0)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecons', to='dfir_formations.formation')),
            ],
            options={
                'ordering': ['formation_id', 'ordre', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProgressionLecon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vu', models.BooleanField(default=False)),
                ('date_vu', models.DateTimeField(blank=True, null=True)),
                ('note_personnelle', models.TextField(blank=True)),
                ('lecon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progressions', to='dfir_elearning.lecon')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progressions', to='dfir_participants.participantdfir')),
            ],
            options={
                'ordering': ['-id'],
                'unique_together': {('participant', 'lecon')},
            },
        ),
    ]
