# Generated by Django 5.2.15 on 2026-08-14 18:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dg_juridique', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TexteReglementaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('intitule', models.CharField(max_length=255)),
                ('statut', models.CharField(choices=[('APPLICABLE', 'Applicable'), ('NON_APPLICABLE', 'Non applicable'), ('A_SURVEILLER', 'À surveiller')], default='APPLICABLE', max_length=20)),
                ('date_analyse', models.DateField(auto_now_add=True)),
                ('synthese', models.TextField(blank=True)),
                ('analyse_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='textes_reglementaires_analyses', to=settings.AUTH_USER_MODEL)),
                ('dossier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='textes_reglementaires', to='dg_juridique.dossierjuridique')),
            ],
            options={
                'ordering': ['-date_analyse'],
            },
        ),
    ]
