# Generated by Django 6.0.5 on 2026-08-14 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_clientprofile_role_comptable'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaboRolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ADMIN', 'Administrateur'), ('GESTIONNAIRE', 'Gestionnaire'), ('TECHNICIEN', 'Technicien'), ('CLIENT', 'Client'), ('FOURNISSEUR', 'Fournisseur'), ('COMPTABLE', 'Comptable')], max_length=20)),
                ('permission_code', models.CharField(max_length=100)),
                ('is_granted', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['role', 'permission_code'],
                'unique_together': {('role', 'permission_code')},
            },
        ),
    ]
