# Generated by Django 5.2.15 on 2026-08-16 17:05

from django.db import migrations, models


def remap_en_attente(apps, schema_editor):
    """L'ancien statut EN_ATTENTE ("En attente") devient A_PLANIFIER ("À
    planifier") dans le nouveau cycle de vie a 10 etats — memes donnees,
    nouveau code/libelle."""
    OrdreTravail = apps.get_model('aero_maintenance', 'OrdreTravail')
    OrdreTravail.objects.filter(statut='EN_ATTENTE').update(statut='A_PLANIFIER')


def revert_remap(apps, schema_editor):
    OrdreTravail = apps.get_model('aero_maintenance', 'OrdreTravail')
    OrdreTravail.objects.filter(statut='A_PLANIFIER').update(statut='EN_ATTENTE')


class Migration(migrations.Migration):

    dependencies = [
        ('aero_maintenance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordretravail',
            name='statut',
            field=models.CharField(choices=[('A_PLANIFIER', 'À planifier'), ('PLANIFIE', 'Planifié'), ('EN_COURS', 'En cours'), ('EN_ATTENTE_PIECE', 'En attente pièce'), ('EN_ATTENTE_CLIENT', 'En attente client'), ('CONTROLE_QUALITE', 'Contrôle qualité'), ('TERMINE', 'Terminé'), ('VALIDE', 'Validé'), ('CLOTURE', 'Clôturé'), ('ANNULE', 'Annulé')], default='A_PLANIFIER', max_length=20),
        ),
        migrations.RunPython(remap_en_attente, revert_remap),
    ]
