# Generated by Django 5.2.15 on 2026-08-16 17:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aero_maintenance', '0002_alter_ordretravail_statut'),
        ('aero_stock', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InterventionTechnique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(choices=[('DIAGNOSTIC', 'Diagnostic'), ('DEMONTAGE', 'Démontage'), ('INSPECTION', 'Inspection'), ('NETTOYAGE', 'Nettoyage'), ('REPARATION', 'Réparation'), ('REMONTAGE', 'Remontage'), ('TEST', 'Test'), ('CONTROLE', 'Contrôle'), ('AUTRE', 'Autre')], default='AUTRE', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Opérations réalisées')),
                ('temps_passe_minutes', models.PositiveIntegerField(default=0)),
                ('mesures', models.TextField(blank=True)),
                ('resultat', models.TextField(blank=True)),
                ('observations', models.TextField(blank=True)),
                ('date_intervention', models.DateTimeField(auto_now_add=True)),
                ('ordre_travail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interventions', to='aero_maintenance.ordretravail')),
                ('pieces_utilisees', models.ManyToManyField(blank=True, related_name='interventions_dae', to='aero_stock.piecerechange')),
                ('technicien', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interventions_dae', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_intervention'],
            },
        ),
    ]
