# Generated by Django 6.0.5 on 2026-08-16 18:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def remap_remplacement(apps, schema_editor):
    """L'ancienne valeur 'REMPLACEMENT' de type_inspection est renommee en
    'REMPLACEMENT_COMPOSANT' (workflow detaille section 8 du cahier des
    charges) — meme pattern que le remap EN_ATTENTE -> A_PLANIFIER deja
    utilise pour OrdreTravail.statut."""
    InspectionRoue = apps.get_model('aero_maintenance', 'InspectionRoue')
    InspectionRoue.objects.filter(type_inspection='REMPLACEMENT').update(type_inspection='REMPLACEMENT_COMPOSANT')


def revert_remap(apps, schema_editor):
    InspectionRoue = apps.get_model('aero_maintenance', 'InspectionRoue')
    InspectionRoue.objects.filter(type_inspection='REMPLACEMENT_COMPOSANT').update(type_inspection='REMPLACEMENT')


class Migration(migrations.Migration):

    dependencies = [
        ('aero_maintenance', '0003_interventiontechnique'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='batterieaeronef',
            name='capacite_nominale',
            field=models.CharField(blank=True, help_text='Ex. 30 Ah', max_length=50),
        ),
        migrations.AddField(
            model_name='batterieaeronef',
            name='reference',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='batterieaeronef',
            name='tension_nominale',
            field=models.CharField(blank=True, help_text='Ex. 24 V', max_length=50),
        ),
        migrations.AddField(
            model_name='batterieaeronef',
            name='type_batterie',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='inspectionroue',
            name='observations',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='inspectionroue',
            name='technicien',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='roueaeronef',
            name='constructeur',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='roueaeronef',
            name='date_derniere_intervention',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='roueaeronef',
            name='prochaine_inspection',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='roueaeronef',
            name='reference',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='roueaeronef',
            name='type_roue',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='inspectionroue',
            name='type_inspection',
            field=models.CharField(choices=[('RECEPTION', 'Réception'), ('IDENTIFICATION', 'Identification'), ('DEMONTAGE', 'Démontage'), ('INSPECTION_PERIODIQUE', 'Inspection périodique'), ('NETTOYAGE', 'Nettoyage'), ('REPARATION', 'Réparation'), ('REMPLACEMENT_COMPOSANT', 'Remplacement de composants'), ('REMONTAGE', 'Remontage'), ('EQUILIBRAGE', 'Équilibrage'), ('CONTROLE_FINAL', 'Contrôle final'), ('VALIDATION', 'Validation')], default='INSPECTION_PERIODIQUE', max_length=25),
        ),
        migrations.CreateModel(
            name='TestBatterie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_test', models.DateTimeField(auto_now_add=True)),
                ('tension_mesuree', models.CharField(blank=True, max_length=50)),
                ('capacite_mesuree', models.CharField(blank=True, max_length=50)),
                ('etat', models.CharField(blank=True, max_length=100)),
                ('temperature', models.CharField(blank=True, max_length=50)),
                ('charge', models.BooleanField(default=False, help_text='Test de charge effectué')),
                ('decharge', models.BooleanField(default=False, help_text='Test de décharge effectué')),
                ('resultat', models.CharField(choices=[('CONFORME', 'Conforme'), ('NON_CONFORME', 'Non conforme'), ('A_REPARER', 'À réparer'), ('A_REMPLACER', 'À remplacer')], default='CONFORME', max_length=15)),
                ('observations', models.TextField(blank=True)),
                ('batterie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='aero_maintenance.batterieaeronef')),
                ('ordre_travail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tests_batteries', to='aero_maintenance.ordretravail')),
                ('technicien', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_test'],
            },
        ),
        migrations.RunPython(remap_remplacement, revert_remap),
    ]
