# Generated by Django 6.0.5 on 2026-08-16 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aero_clients', '0004_aeronef_annee_fabrication_aeronef_constructeur_and_more'),
        ('aero_maintenance', '0004_batterieaeronef_capacite_nominale_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipementAeronautique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, max_length=50)),
                ('numero_serie', models.CharField(max_length=50, unique=True)),
                ('type_equipement', models.CharField(choices=[('ELECTRIQUE', 'Équipement électrique'), ('HYDRAULIQUE', 'Équipement hydraulique'), ('MECANIQUE', 'Équipement mécanique'), ('AUTRE', 'Autre équipement aéronautique')], default='AUTRE', max_length=15)),
                ('fabricant', models.CharField(blank=True, max_length=255)),
                ('modele', models.CharField(blank=True, max_length=255)),
                ('proprietaire', models.CharField(blank=True, help_text="Si différent de l'exploitant (client)", max_length=255)),
                ('statut', models.CharField(choices=[('EN_SERVICE', 'En service'), ('EN_CONTROLE', 'En contrôle'), ('REPARE', 'Réparé'), ('REMPLACE', 'Remplacé'), ('NON_CONFORME', 'Non conforme')], default='EN_SERVICE', max_length=20)),
                ('date_reception', models.DateField(auto_now_add=True)),
                ('aeronef', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipements_aeronautiques', to='aero_clients.aeronef')),
            ],
            options={
                'ordering': ['numero_serie'],
            },
        ),
    ]
