# Generated by Django 6.0.5 on 2026-08-16 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aero_maintenance', '0005_equipementaeronautique'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificatDAE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, max_length=50, unique=True)),
                ('date_emission', models.DateTimeField(auto_now_add=True)),
                ('ordre_travail', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certificat', to='aero_maintenance.ordretravail')),
            ],
            options={
                'ordering': ['-date_emission'],
            },
        ),
    ]
