# Generated by Django 6.0.5 on 2026-08-16 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aero_maintenance', '0006_certificatdae'),
    ]

    operations = [
        migrations.AddField(
            model_name='batterieaeronef',
            name='prochain_controle',
            field=models.DateField(blank=True, help_text='Échéance du prochain contrôle/test', null=True),
        ),
    ]
