# Generated by Django 5.2.15 on 2026-08-16 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aero_clients', '0002_demandedae'),
        ('aero_finance', '0001_initial'),
        ('aero_maintenance', '0003_interventiontechnique'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturedae',
            name='frais_supplementaires',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='facturedae',
            name='montant_main_oeuvre',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='facturedae',
            name='montant_pieces',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='facturedae',
            name='taux_tva',
            field=models.DecimalField(decimal_places=2, default=18, max_digits=5),
        ),
        migrations.CreateModel(
            name='BonCommandeDAE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=50, unique=True)),
                ('montant_ttc', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente de signature'), ('SIGNE', 'Signé'), ('ANNULE', 'Annulé')], default='EN_ATTENTE', max_length=10)),
                ('date_creation', models.DateField(auto_now_add=True)),
                ('date_signature', models.DateField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bons_commande', to='aero_clients.clientaeronautique')),
                ('ordre_travail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bons_commande', to='aero_maintenance.ordretravail')),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
        migrations.AddField(
            model_name='facturedae',
            name='bon_commande',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factures', to='aero_finance.boncommandedae'),
        ),
        migrations.CreateModel(
            name='DevisDAE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('montant_main_oeuvre', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('montant_pieces', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('frais_supplementaires', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('taux_tva', models.DecimalField(decimal_places=2, default=18, max_digits=5)),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('ENVOYE', 'Envoyé'), ('ACCEPTE', 'Accepté'), ('REFUSE', 'Refusé'), ('EXPIRE', 'Expiré')], default='BROUILLON', max_length=10)),
                ('date_creation', models.DateField(auto_now_add=True)),
                ('date_validite', models.DateField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devis', to='aero_clients.clientaeronautique')),
                ('ordre_travail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devis', to='aero_maintenance.ordretravail')),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
        migrations.AddField(
            model_name='boncommandedae',
            name='devis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bons_commande', to='aero_finance.devisdae'),
        ),
    ]
