# Generated by Django 5.2.15 on 2026-08-14 16:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompteEmailDFIR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_compte', models.CharField(choices=[('gmail', 'Gmail'), ('outlook', 'Outlook / Office 365'), ('yahoo', 'Yahoo Mail'), ('imap', 'IMAP personnalisé')], default='imap', max_length=10)),
                ('nom_affichage', models.CharField(blank=True, max_length=255)),
                ('adresse_email', models.EmailField(max_length=254)),
                ('identifiant', models.CharField(blank=True, help_text="Si différent de l'adresse email", max_length=255)),
                ('mot_de_passe', models.CharField(blank=True, max_length=255)),
                ('serveur_entrant', models.CharField(blank=True, max_length=255, verbose_name='Serveur IMAP')),
                ('port_entrant', models.PositiveIntegerField(default=993)),
                ('ssl_entrant', models.BooleanField(default=True)),
                ('serveur_sortant', models.CharField(blank=True, max_length=255, verbose_name='Serveur SMTP')),
                ('port_sortant', models.PositiveIntegerField(default=587)),
                ('ssl_sortant', models.BooleanField(default=True)),
                ('est_principal', models.BooleanField(default=False)),
                ('statut', models.CharField(choices=[('INACTIF', 'Inactif'), ('ACTIF', 'Actif'), ('ERREUR', 'Erreur')], default='INACTIF', max_length=10)),
                ('derniere_synchro', models.DateTimeField(blank=True, null=True)),
                ('derniere_erreur', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comptes_email_dfir', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-est_principal', 'adresse_email'],
            },
        ),
        migrations.CreateModel(
            name='EmailDFIR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('ENTRANT', 'Entrant'), ('SORTANT', 'Sortant')], default='ENTRANT', max_length=10)),
                ('message_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('thread_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('sujet', models.CharField(blank=True, max_length=500)),
                ('expediteur_nom', models.CharField(blank=True, max_length=255)),
                ('expediteur_email', models.EmailField(blank=True, max_length=254)),
                ('destinataires', models.JSONField(blank=True, default=list)),
                ('destinataires_cc', models.JSONField(blank=True, default=list)),
                ('corps_texte', models.TextField(blank=True)),
                ('corps_html', models.TextField(blank=True)),
                ('date_message', models.DateTimeField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('NON_LU', 'Non lu'), ('LU', 'Lu'), ('REPONDU', 'Répondu'), ('ARCHIVE', 'Archivé')], default='NON_LU', max_length=10)),
                ('priorite', models.CharField(choices=[('NORMALE', 'Normale'), ('HAUTE', 'Haute'), ('URGENTE', 'Urgente')], default='NORMALE', max_length=10)),
                ('score_urgence', models.PositiveSmallIntegerField(default=0)),
                ('resume_ia', models.TextField(blank=True)),
                ('actions_detectees', models.JSONField(blank=True, default=list)),
                ('traite_par_ia', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('compte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='dfir_email.compteemaildfir')),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('en_reponse_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reponses', to='dfir_email.emaildfir')),
            ],
            options={
                'ordering': ['-date_message', '-created_at'],
                'unique_together': {('compte', 'message_id')},
            },
        ),
        migrations.CreateModel(
            name='PieceJointeEmailDFIR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_fichier', models.CharField(max_length=255)),
                ('fichier', models.FileField(upload_to='dfir_email/pieces_jointes/%Y/%m/')),
                ('type_mime', models.CharField(blank=True, max_length=100)),
                ('taille', models.PositiveIntegerField(default=0)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pieces_jointes', to='dfir_email.emaildfir')),
            ],
        ),
    ]
