# Generated by Django 5.2.15 on 2026-08-14 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dfir_email', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compteemaildfir',
            name='mot_de_passe',
            field=models.TextField(blank=True),
        ),
    ]
