# Generated by Django 6.0.5 on 2026-08-16 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aero_qualite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actioncorrectivedae',
            name='analyse_cause',
            field=models.TextField(blank=True, help_text='Analyse de la cause racine de la non-conformité'),
        ),
        migrations.AddField(
            model_name='actioncorrectivedae',
            name='date_verification',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='actioncorrectivedae',
            name='efficace',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='actioncorrectivedae',
            name='verification_efficacite',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='nonconformitedae',
            name='cause',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='nonconformitedae',
            name='date_echeance',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nonconformitedae',
            name='origine',
            field=models.CharField(choices=[('CONTROLE_QUALITE', 'Contrôle qualité'), ('AUDIT', 'Audit'), ('INTERVENTION', 'Intervention'), ('CLIENT', 'Client'), ('INCIDENT', 'Incident')], default='CONTROLE_QUALITE', max_length=20),
        ),
        migrations.AlterField(
            model_name='actioncorrectivedae',
            name='statut',
            field=models.CharField(choices=[('PLANIFIEE', 'Planifiée'), ('EN_COURS', 'En cours'), ('REALISEE', 'Réalisée'), ('VERIFIEE', 'Efficacité vérifiée'), ('CLOTUREE', 'Clôturée')], default='PLANIFIEE', max_length=10),
        ),
    ]
